### PR TITLE
Feature/rewrite acl

### LINKED ISSUE #47: ACLs various issues
From Taranis-NG created by [ewoiset](https://github.com/ewoiset): ait-cs-IaaS/Taranis-NG#68  

There are various issues with creating and updating ACLs, that should be tested.

- [ ] roles and users not stored in dictionary
- [ ] "everyone" is automatically set to true, even if it is not set 
- [ ] update throws sql error: 
```
sqlalchemy.exc.StatementError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(builtins.LookupError) '1' is not among the defined enum values. Enum name: itemtype. Possible values: OSINT_SOURC.., OSINT_SOURC.., WORD_LIST, ..., DELEGATION
[SQL: UPDATE acl_entry SET item_type=%(item_type)s WHERE acl_entry.id = %(acl_entry_id)s]

``` 

- [ ] update tests

### PR DESCRIPTION
**Pull request by b3n4kh**
This PR Fixes #47 #86 

ACLEntry has been renamed to "RoleBasedAccess", with the goal to in the feature make it easier to implement "real" RBAC as a access control in Taranis AI, the changes in this PR should lay the foundation in this direction.

Features:
An Administrator with the correct permssion: 

```
  CONFIG_ACL_ACCESS
  CONFIG_ACL_CREATE
  CONFIG_ACL_UPDATE
  CONFIG_ACL_DELETE
```

Can update or create ACLs under `/config/acls`.

He has to provide an item type, item id, unique name, and a role to assign the acl to.

image

> [!IMPORTANT]
For backwards compatibility ACLs are only active if there is at least on ACL for a specific item_type.
This information is shown on top of the ACL page.

If there is an ACL for a specific type only these roles are allowed to read, and if 'write' flag is set, also write the given resource.

## Summary by CodeRabbit

- **New Features**
	- Introduced role-based access control across various models and APIs.
	- Added TLP (Traffic Light Protocol) level parameter to collectors and roles.
	- Enhanced user profile management with new attributes and simplified update logic.
	- Updated product and report item management with role-based access and improved query methods.
	- Streamlined ACL (Access Control List) handling with role-based access across the system.
- **Improvements**
	- Refined authentication checks to enhance security.
	- Optimized file download logic for news items.
	- Improved type annotations and relationship definitions across models for better clarity and maintenance.
	- Updated GUI components for better user interaction and accessibility.
	- Enhanced test cases to cover new functionalities and access control changes.
- **Bug Fixes**
	- Fixed issue with search functionality in OSINT sources and word lists.
	- Addressed user update profile logic to correctly delegate to the user profile update method.
- **Refactor**
	- Consolidated resource paths and removed redundant code across various API endpoints.
	- Simplified conditional logic in user update method using named expressions.
	- Refactored access control logic to use new role-based access control service.
- **Style**
	- Updated GUI components' layout and interaction elements for a better user experience.
- **Chores**
	- Removed unused imports and updated dependencies.
- **Documentation**
	- Updated ACL-related messages and usage information in GUI to reflect new access control terminology.

### CODE REVIEW

**Comment by ewoiset** [comment]
@b3n4kh  I rebuild the DB, do i need to do sth more, because i found following issues:
- ACL can't be edited -> AttributeError: 'int' object has no attribute '_sa_instance_state'
- ACL can be created without selecting roles 
- if reports were created and afterwards ACLs defined, one gets an internal server error on analyze endpoint 
- as soon as a ACL report is created for a role the user can't create a report anymore, also if item type = product type etc. (for all) 
- However, a product can be created (but are not displayed) - and reports created before the ACL are displayed 
- After removing all ACLs,  products are still not displayed --> Bad Request

I stopped testing here (only tested with admin user) 

remark: 
- story clustering -> what will the behaviour be? - or is this issue only restricted to reports/products?

**Comment by b3n4kh** [comment]
> @b3n4kh I rebuild the DB, do i need to do sth more, because i found following issues:
> 
> * ACL can't be edited -> AttributeError: 'int' object has no attribute '_sa_instance_state'

Can not reproduce, where is this error thrown? The [automatic tests](https://github.com/taranis-ai/taranis-ai/blob/master/src/core/tests/functional/test_config.py) do not trigger this on my machines as well as in the CI/CD!
Does the TestAcls fail as well on your machine?

> * ACL can be created without selecting roles

I will raise this with at the next meeting, how this should behave.

> * if reports were created and afterwards ACLs defined, one gets an internal server error on analyze endpoint
> * as soon as a ACL report is created for a role the user can't create a report anymore, also if item type = product type etc. (for all)
> * However, a product can be created (but is not displayed) - and reports created before the ACL are displayed in the product creation
> * After removing all ACLs,  products are still not displayed --> Bad Request

What is the error thrown here? After looking at the code again I might have identified an issue with a missing typecast in the `filter_query_with_acl` where the `id` is Integer instead of `String`.




> I stopped testing here (only tested with admin user)
> 
> remark:
> 
> * story clustering -> what will the behaviour be? - or is this issue only restricted to reports/products?

NewsItems could be affected only by OSINTSource rules.

**Comment by b3n4kh** [comment]
I added some type casts in `filter_query_with_acl`, maybe you can add some stack traces, as to what is happening on your end, to narrow this down.

**Comment by ewoiset** [comment]
> Can not reproduce, where is this error thrown? The [automatic tests](https://github.com/taranis-ai/taranis-
> ai/blob/master/src/core/tests/functional/test_config.py) do not trigger this on my machines as well as in the CI/CD!
> Does the TestAcls fail as well on your machine?

- Create new ACL 
- Edit & update e.g. Title 
- Refresh page --> old title appears

**Comment by ewoiset** [comment]
> What is the error thrown here? After looking at the code again I might have identified an issue with a missing typecast in the 
> filter_query_with_acl where the id is Integer instead of String.

Now the behavior is as following: 
- Reports created before the ACL are visible 
- Reports can be created after ACL is deleted 

but: 
- Reports can't be created as soon as a ACL is created - it does not matter which type of ACL is selected - is this a wished behavior? - error message: api_service.js:60 
 POST http://localhost:5000/api/analyze/report-items 403 (FORBIDDEN

Product was created before ACL 
- error on publish endpoint:  GET http://localhost:5000/api/publish/products? 400 (BAD REQUEST) AxiosError

When ACL/Product Type is created --> no products (and not only the selected ID) can't be created --> no product type can be selected in "create new product"

**Pull request merged**
