### PR TITLE
Feature/story bot extensions

### PR DESCRIPTION
**Pull request by ewoiset**
- Split-up initial clustering in two parts. 
- update story clustering version --> newest incremental clustering 

please install new dependencies 

## Summary by CodeRabbit

- **New Features**
	- Enhanced story bot functionality for improved clustering of stories, including asynchronous initial clustering and event handling for clustering events.

### CODE REVIEW

**Review by b3n4kh — CHANGES_REQUESTED** [review]
Is there a reason to not use the [CorpusEncoder](https://github.com/taranis-ai/story-clustering/blob/db1ddcdcbfef5e0dbbfd8985c3a271065240e2d1/story_clustering/document_representation.py#L191) from here?

```python
from story_clustering.document_representation import CorpusEncoder

corpus_json = json.dumps(corpus, cls=CorpusEncoder)
initial_clustering.delay(corpus_json)
```

We could avoid adding another dependency and mitigate the security concerns raised by coderabbit.

**Comment by ewoiset** [comment]
@b3n4kh as this does not seem correctly implemented and throws an `AttributeError: 'dict' object has no attribute 'docs'`

I talked to Medina, maybe we can change it in the future when there is time

**Comment by b3n4kh** [comment]
> Is there a reason to not use the [CorpusEncoder](https://github.com/taranis-ai/story-clustering/blob/db1ddcdcbfef5e0dbbfd8985c3a271065240e2d1/story_clustering/document_representation.py#L191) from here?
> 
> ```python
> from story_clustering.document_representation import CorpusEncoder
> 
> corpus_json = json.dumps(corpus, cls=CorpusEncoder)
> initial_clustering.delay(corpus_json)
> ```
> 
> We could avoid adding another dependency and mitigate the security concerns raised by coderabbit.

https://github.com/taranis-ai/story-clustering/blob/0ef6fb0facf9d72e200148320453d30e76ad63f7/story_clustering/tests/test_clustering.py#L44

**Comment by ewoiset** [comment]
@b3n4kh should be fixed now

**Pull request merged**
